version: "3"

services:
  webserver1:
    image: httpd
    networks:
      - trkcll
    volumes:
      - "/Users/mganitombalak/Github/training/Docker/TRKCLL/webserver1/:/usr/local/apache2/htdocs/"
    depends_on: 
      - webserver2
  
  webserver2:
    image: httpd
    networks:
      - trkcll
    volumes:
      - "/Users/mganitombalak/Github/training/Docker/TRKCLL/webserver2/:/usr/local/apache2/htdocs/"

  loadbalancer:
    image: nginx
    ports:
      - "80:80"
    networks:
      - trkcll
    volumes:
      - "/Users/mganitombalak/Github/training/Docker/TRKCLL/nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on: 
      - webserver1


networks:
  trkcll: