version: "3.7"

services:
  webserver1:
    image: httpd
    volume:
     - "/home/ubuntu/webserver1:/usr/local/apache2/htdocs"
    networks:
      - trkcll

  webserver2:
    image: httpd
    volumes:
     - "/home/ubuntu/webserver2:/usr/local/apache2/htdocs"
    networks:
      - trkcll

  loadbalancer:
    image: nginx
    ports:
     -"80:80"
    volume:
     - "/home/ubuntu/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - trkcll

networks:
  trkcll:
