version: "3"

services:
  webserver1:
    build:
      context: ./server1
    #image: httpd
    networks: 
      - sqills
   # volumes:
   #  - ./server1:/usr/local/apache2/htdocs
   # depends_on: 
    #  - loadbalancer

  webserver2:
    build:
      context: ./server2
    #image: httpd
    networks:
      - sqills
    #volumes:
    #  - ./server2:/usr/local/apache2/htdocs
    #depends_on: 
     # - loadbalancer

  loadbalancer:
    build:
      context: ./nginx
    #image: nginx
    networks:
      - sqills
    ports:
      - 80:80
    depends_on: 
      - webserver1
      - webserver2
    #volumes:
     # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
networks: 
  sqills: