version: "3"

services:
  mysite:
    image: drupal:latest
    networks:
      - sqills
    ports:
      - "80:80"
  mydb:
    image: postgres
    networks :
     - sqills
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=mypasswd
networks:
  sqills: