version: "3"

services:
  mysite:
    image: drupal:latest
    networks:
      - isnet
    ports:
      - "80:80"
  mydb:
    image: postgres
    networks :
     - isnet
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=mypasswd
networks:
  isnet: