version: "3"

services:
  myapi1:
    build: .
    networks: 
    - isnet-crm

  myapi2:
    build: .
    networks: 
    - isnet-crm

  loadbalancer:
    image: nginx
    networks:
    - isnet-crm
    ports:
    - "80:80"
    volumes:
    -  "/Users/mganitombalak/Github/training/Docker/Isnet/nginx/nginx.conf:/etc/nginx/nginx.conf"

networks:
  isnet-crm: